#:schema node_modules/wrangler/config-schema.json
name = "r2-ingress"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

account_id = "2dc3483aa62d4b5dc774ec04713893de"

workers_dev = false
routes = [
    { pattern = "db.poi.moe/*", zone_name = "poi.moe" },
    { pattern = "nightlies.poi.moe/*", zone_name = "poi.moe" },
]

r2_buckets  = [
    { binding = "BUCKET_POI_DB", bucket_name = "poi-db"},
    { binding = "BUCKET_POI_NIGHTLIES", bucket_name = "poi-nightlies"},
]

services = [
  { binding = "FRONTEND", service = "r2-index" }
]

[observability]
enabled = true
